### ISSUE TITLE
Warehouse Duplication

### ISSUE THREAD

**Issue by oversword** [joe7575/techpack#42] opened 2019-12-18 20:57 UTC
Warehouses, specifically gold warehouses (techpack) can be used to duplicate items infinitely (so long as you have at least 3 items)

To replicate:

1. Place a warehouse and collect 3 of the same item.
2. Use one of the items to configure the fist slot of the warehouse (left-right)
3. Put the other 2 items in the warehouse and let them find their slot
4. Pick up the 2 items and scroll up and down quickly
5. You should now have 4 items in your inventory
6. Rinse and repeat to duplicate infinitely

- This bug depends on the speed you scroll
- The normal scrolling behaviour is to put items from the stack in your inventory one by one
- The warehouse overrides this behaviour to put a full stack on each scroll (if possible)
- This has already been fixed (submitting immanently) by getting the `main_stack` from the `node_inv` each time `move_to_player_inv` is called instead of passing it in

**Comment by oversword** [comment] 2019-12-18 21:16
Pull request: https://github.com/joe7575/techpack/pull/43

**Comment by joe7575** [comment] 2019-12-21 11:39
I can't reproduce it. What do you mean with "scroll up and down"? With the mouse wheel?
Nothing happens on my PC when I use the mouse wheel on any inventory item...
But anyhow, I merged your pull request. Thanks for the fix.

**Closed by joe7575** 2019-12-21 11:39 UTC

**Comment by oversword** [comment] 2019-12-23 18:18
Yeah scrolling with the mouse wheel.
I mean placing the item into your inventory with a scroll:
Picking it up, moving it over your inventory, then scrolling over an empty inventory slot with the stack.

Other experienced players were surprised by this behaviour too, they may have added scrolling in 5.x

Anyway as I'm sure you can see my code can't hurt and just corrects a passing-by-copy issue, which is only functional if it's synchronous! 

You may also be able to replicate this (in the pre-merged version) by right-clicking the stack into your inventory very quickly, this is hard to replicate without there being much lag however.

**Comment by oversword** [comment] 2021-01-12 20:13
Dead issue I know, but I think I figured out what was really going on and why you couldn't replicate it.
I'm using a wireless keyboard with an inbuilt touch-pad, and using the touch-pad to produce this error.
After a little more experience with the touch-pad I'm certain it's actually pretending to be a normal mouse to the computer - that it's using its own gesture recognition firmware, and is sending mouse events to the computer once it thinks it's figured out what to do.

In relation to the issue, this means that if I scroll really fast, I don't send a single scroll event with a delta of like 70, I send 70 scroll events with a delta of 1 in ridiculously quick succession. A normal mouse would send these events one at a time with each click of the wheel, a normal touch-pad would wait briefly so it can poll and figure out a velocity, smoothing things out - but the touch-pad masquerading as a mouse is sending the events in an unexpected way.

It's likely that a normal mouse / touch-pad is not sending events fast enough to out-race the minetest delay, but my peculiar mouse is sending many events in one go.

Either way, better safe than sorry, this fix is still required as I could find some autoclicker software to produce the events quickly enough I'm sure.
